app:
  port: 8081
  data_path: "./data"
  ui_enabled: true
  ui_password: "changeme"
  debug: false
  jwt_secret: "your-very-secure-jwt-secret-key-here"
  magnet_to_torrent_enabled: true
  magnet_to_torrent_timeout: 60
  filter_log_level: "detail"

torrent_client:
  type: "transmission" # or "qbittorrent"
  host: "localhost:9091" # e.g., localhost:8080 for qbittorrent
  username: ""
  password: ""
  download_path: "/downloads/media"

notifications:
  pushbullet:
    api_key: ""

extra_trackers_list:
  - udp://tracker-1
  - upd://tracker-2

metadata:
  language: "en"
  tmdb:
    api_key: "your_tmdb_api_key_here"
  imdb:
    api_key: "" # Placeholder for future use
  tvmaze:
    api_key: "" # No key needed for basic use
  anilist: {} # No config needed for public queries
  trakt:
    client_id: "your_trakt_client_id_here"
  anidb: {} # No config needed for public queries

movies:
  providers: ["tmdb", "imdb"] # Order of preference
  download_folder: "/downloads/movies"
  destination_folder: "/media/movies"
  move_method: "move" # or "symlink"
  sources:
    - type: "scarf"
      url: "http://localhost:8080/torznab/movies"
      api_key: "your_scarf_api_key_here"
    - type: "rss"
      url: "https://example.com/rss.xml"
    - type: "prowlarr"
      url: "http://prowlarr:9696"
      api_key: "your_prowlarr_api_key_here"

tv-shows:
  providers: ["tvmaze"]
  download_folder: "/downloads/shows"
  destination_folder: "/media/shows"
  move_method: "move" # or "symlink"
  sources:
    - type: "scarf"
      url: "http://localhost:8080/torznab/tv"
      api_key: "your_scarf_api_key_here"

anime:
  providers: ["anidb"]
  download_folder: "/downloads/anime"
  destination_folder: "/media/anime"
  move_method: "move" # or "symlink"
  sources:
    - type: "scarf"
      url: "http://localhost:8080/torznab/anime"
      api_key: "your_scarf_api_key_here"

database:
  path: "./data/reel.db"

automation:
  search_interval: "1h"
  episode_download_delay_hours: 8
  max_concurrent_downloads: 3
  quality_preferences:
    - "1080p"
    - "720p"
  min_seeders: 5
  keep_torrents_for_days: 7
  keep_torrents_seed_ratio: 1.2
  notifications: [] # e.g., ["pushbullet"]
  reject-common:
  - \bscreener\b
  - \bhdcam\b
  - \btelecine\b